package pl.interpreter;

public enum TokenType {
    KEYWORD,
    IDENTIFIER,
    CONSTANT,
    LEFT_CURLY_BRACKET,
    RIGHT_CURLY_BRACKET,
    LEFT_PARENTHESES,
    RIGHT_PARENTHESES,
    SEMICOLON,
    COMMA,
    ARROW,
    ADDITIVE_OPERATOR,
    MULTIPLICATIVE_OPERATOR,
    RELATIONAL_OPERATOR,
    ASSIGNMENT,
    DOT,
    EOF
}
